enum OTHERS {
  SPLASHSCREEN = 'SPLASHSCREEN',
  CINEMATIC_1 = 'CINEMATIC_1',
  CINEMATIC_2 = 'CINEMATIC_2',
  CINEMATIC_3 = 'CINEMATIC_3',
  TUTORIAL = 'TUTORIAL',
  END = 'END',
}

export default OTHERS
