enum TRANSITIONS {
  TRANSITION_1 = 'TRANSITION_1',
  TRANSITION_2 = 'TRANSITION_2',
  TRANSITION_3 = 'TRANSITION_3',
  TRANSITION_4 = 'TRANSITION_4',
  TRANSITION_5 = 'TRANSITION_5',
}

export default TRANSITIONS
