import ORDALIES from '@/constants/ORDALIES'

export default {
  [ORDALIES.CROIX]: [
    'Je soussygnez, moy, Enguerrand le Bienventru, lègue mon fouet, ma cuillèr en bois et ma casserole à mon cherz second, puisse la grâce l’épargnez d’oublier la cerise sur le gasteau !',
    'O sire, puysse ma trèz célèbre recette de ragoutz de boudain estre preservé a jamais et restez dans les mèmoir de touz ceux qui onz eu la joy dy goûter !',
    'Pour confectionnez un flan aux pruneau, il vous fauds des oeufs fraiz de la matinée, du lait tiréz des éstable du chasteau, ez des pruneau d’un diamètre équidvalant à un écu.',
    'Chanceux es le biensheureux qui jouy de l’insouciance de la libertéz, puis que je n’atens plus que l’heure de la mort, asfin de festoyer de vin et de ragoutz au paradiz des cuisiniez.',
  ],
  [ORDALIES.BBQ]: [
    'Attrapoire',
    'Ardre',
    'Batelage',
    'Bigre',
    'Carnade',
    'Chiaberna',
    'Deable',
    'Douloir',
    'Esbigner',
    'Estrapade',
    'Fallace',
    'Fredain',
    'Gorrin',
    'Grevain',
    'Quarteler',
    'Merdaille',
    'Mordiable',
    'Porpisser',
    'Por-Diu',
    'Trouiller',
    'Tudieu',
    'Vain-dieu',
    'Vergogne',
  ],
  [ORDALIES.FOOD]: [
    'Attrapoire',
    'Ardre',
    'Batelage',
    'Bigre',
    'Carnade',
    'Chiaberna',
    'Deable',
    'Douloir',
    'Esbigner',
    'Estrapade',
    'Fallace',
    'Fredain',
    'Gorrin',
    'Grevain',
    'Quarteler',
    'Merdaille',
    'Mordiable',
    'Porpisser',
    'Por-Diu',
    'Trouiller',
    'Tudieu',
    'Vain-dieu',
    'Vergogne',
  ],
}
