import ORDALIES from '@/constants/ORDALIES'

export default {
  [ORDALIES.CROIX]: [
    "Priés pour nous trespassez, vous qui vivez, et nous aidez en la vertu de charité, n'est rienz que tant vaille a nostre délivrance come la vertu de cherité, de pitié et de perdon.",
    "Sire, envoiez vous sainz ainglez de paradix a moy, por me défendre, enluminer et eschaufier en l'amour de la veritey et la bialtey que est en ce saint sacrement contenu.",
    "O vous mors qui gisés es sepulchrez, levez vous, sire aidés moy, perdonnez moy, confortez moy, aies merci de moy. Ainsi soit il, c'est amen.",
  ],
  [ORDALIES.BBQ]: [
    'Attrapoire',
    'Ardre',
    'Batelage',
    'Bigre',
    'Carnade',
    'Chiaberna',
    'Deable',
    'Douloir',
    'Esbigner',
    'Estrapade',
    'Fallace',
    'Fredain',
    'Gorrin',
    'Grevain',
    'Quarteler',
    'Merdaille',
    'Mordiable',
    'Porpisser',
    'Por-Diu',
    'Trouiller',
    'Tudieu',
    'Vain-dieu',
    'Vergogne',
  ],
  [ORDALIES.FOOD]: [
    'Attrapoire',
    'Ardre',
    'Batelage',
    'Bigre',
    'Carnade',
    'Chiaberna',
    'Deable',
    'Douloir',
    'Esbigner',
    'Estrapade',
    'Fallace',
    'Fredain',
    'Gorrin',
    'Grevain',
    'Quarteler',
    'Merdaille',
    'Mordiable',
    'Porpisser',
    'Por-Diu',
    'Trouiller',
    'Tudieu',
    'Vain-dieu',
    'Vergogne',
  ],
}
